# Generated by Django 5.2.8 on 2025-11-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_categoria_tarea_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='color_etiqueta',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
